"""Shared runner for guard smoke checks.

NOTHING HERE IS EXECUTED. A case is a JSON description of a call an agent is about to
make. It goes to the guard on stdin, the guard answers allow/deny, and that is the whole
test. Commands are never run and paths are never opened — not even when the expected
answer is ALLOW. The only process started is the guard itself.

Paths in the cases are synthetic strings. The guard inspects them as text and never opens
them, so no real path — least of all a real key location — belongs in a case.

Run a test file with no arguments to check the live guard, or with `preview` to check the
file regenerated by `task generate-plan`, leaving the live one untouched.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path
from typing import Any, NamedTuple

DENY = "deny"
ALLOW = "allow"
PREVIEW_MODE = "preview"

HookPayload = dict[str, Any]


class Case(NamedTuple):
    """One smoke check: what we send the guard and what it must answer."""

    expected: str  # DENY or ALLOW
    name: str  # shown in the report
    payload: HookPayload  # JSON sent to the guard on stdin


def proposed_bash(value: str) -> HookPayload:
    """A Bash call an agent is about to make. The string is never executed."""
    return {"hook_event_name": "PreToolUse", "tool_input": {"command": value}}


def proposed_bash_in(directory: str, value: str) -> HookPayload:
    """Same, but the session claims to sit in the given directory."""
    payload = proposed_bash(value)
    payload["cwd"] = directory
    return payload


def proposed_read(value: str) -> HookPayload:
    """A Read/Edit call. The path is never opened."""
    return {"hook_event_name": "PreToolUse", "tool_input": {"file_path": value}}


def proposed_write(path: str, content: str) -> HookPayload:
    """A Write call. Nothing is written to disk."""
    return {
        "hook_event_name": "PreToolUse",
        "tool_name": "Write",
        "tool_input": {"file_path": path, "content": content},
    }


def proposed_edit(path: str, new_string: str) -> HookPayload:
    """An Edit call. Nothing on disk is changed."""
    return {
        "hook_event_name": "PreToolUse",
        "tool_name": "Edit",
        "tool_input": {"file_path": path, "new_string": new_string},
    }


def tool_output(value: Any, command: str | None = None) -> HookPayload:
    """A result a tool has already returned."""
    payload: HookPayload = {"hook_event_name": "PostToolUse", "tool_response": value}
    if command is not None:
        payload["tool_input"] = {"command": command}
    return payload


def pick_guard(guard: Path, argv: list[str]) -> Path:
    if not argv:
        return guard

    if argv[0] != PREVIEW_MODE:
        raise SystemExit(f"unknown mode: {argv[0]}; expected {PREVIEW_MODE}")

    preview = guard.with_name(f"{guard.stem}.test_generated{guard.suffix}")
    if not preview.exists():
        raise SystemExit(
            f"preview guard is missing: {preview}; run `task generate-plan`"
        )

    return preview


def decide(guard: Path, payload: HookPayload) -> str:
    result = subprocess.run(
        [sys.executable, str(guard)],
        input=json.dumps(payload),
        capture_output=True,
        text=True,
        timeout=10,
    )
    return ALLOW if not result.stdout.strip() else DENY


def run(guard: Path, cases: list[Case], argv: list[str]) -> int:
    target = pick_guard(guard, argv)
    print(f"guard: {target.name}\n")

    failed = 0
    for expected, name, payload in cases:
        actual = decide(target, payload)
        if actual == expected:
            print(f"  ok      {name:<36} {actual}")
        else:
            print(f"  FAIL    {name:<36} ожидали {expected}, получили {actual}")
            failed += 1

    print(f"\nитого: {len(cases) - failed} ok, {failed} fail")
    return 1 if failed else 0
